classDiagram
LoginScreen --> AuthenticationController
MenuManagementScreen --> MenuManagementController
MenuManagementScreen --> MenuItem
AddEditMenuForm --> MenuItem
MenuManagementController --> MenuItem
AuthenticationController --> User